In [1]:
train_path = 'C:\\Users\\Administrator\\Desktop\\Code_Test\\Research\\Surveys-Missing-Data-Imputation--master\\data_K_Fold\\abalone\\train\\data_missing_40\\train_1.csv'

In [2]:
import numpy as np
import random

In [3]:
X_train = np.genfromtxt(train_path, delimiter=',')
X_train

array([[   nan,    nan,    nan, ...,    nan,    nan,  3.   ],
       [ 0.67 ,  0.51 ,  0.175, ...,  0.345, 10.   ,  3.   ],
       [ 0.67 ,  0.5  ,  0.19 , ...,  0.415, 10.   ,  3.   ],
       ...,
       [   nan,  0.43 ,  0.15 , ...,  0.22 ,  8.   ,  1.   ],
       [ 0.62 ,  0.485,    nan, ...,  0.352,  9.   ,  1.   ],
       [   nan,    nan,    nan, ...,  0.34 ,    nan,  3.   ]])

In [4]:
test_path = 'C:\\Users\\Administrator\\Desktop\\Code_Test\\Research\\Surveys-Missing-Data-Imputation--master\\data_K_Fold\\abalone\\test\\data_missing_40\\test_1.csv'

In [5]:
X_test = np.genfromtxt(test_path, delimiter=',')
X_test

array([[    nan,  0.195 ,  0.09  , ...,  0.0355,     nan,  2.    ],
       [    nan,     nan,     nan, ...,     nan,     nan,  3.    ],
       [ 0.66  ,  0.53  ,     nan, ...,     nan,     nan,  1.    ],
       ...,
       [    nan,     nan,     nan, ...,     nan,     nan,  2.    ],
       [    nan,     nan,     nan, ...,     nan,     nan,  3.    ],
       [ 0.49  ,  0.39  ,  0.15  , ...,  0.17  , 21.    ,  3.    ]])

In [6]:
X_train[:, -1]

array([3., 3., 3., ..., 1., 1., 3.])

In [7]:
from sklearn.impute import SimpleImputer
import pandas as pd
imp_mean = SimpleImputer( strategy='mean')
imp_mean.fit(X_train[:,:7], X_train[:,-1])
imputed_train_df = imp_mean.transform(X_test[:, :7])
pd.DataFrame(X_test[:,-1])

0
0    2.0
1    3.0
2    1.0
3    1.0
4    2.0
..   ...
829  2.0
830  3.0
831  2.0
832  3.0
833  3.0

[834 rows x 1 columns]

In [8]:
from sklearn.impute import KNNImputer

In [9]:
X_train

array([[   nan,    nan,    nan, ...,    nan,    nan,  3.   ],
       [ 0.67 ,  0.51 ,  0.175, ...,  0.345, 10.   ,  3.   ],
       [ 0.67 ,  0.5  ,  0.19 , ...,  0.415, 10.   ,  3.   ],
       ...,
       [   nan,  0.43 ,  0.15 , ...,  0.22 ,  8.   ,  1.   ],
       [ 0.62 ,  0.485,    nan, ...,  0.352,  9.   ,  1.   ],
       [   nan,    nan,    nan, ...,  0.34 ,    nan,  3.   ]])

In [10]:
imputer = KNNImputer(n_neighbors=10)
imputer.fit_transform(X_test)

array([[ 0.3595 ,  0.195  ,  0.09   , ...,  0.0355 ,  6.2    ,  2.     ],
       [ 0.5225 ,  0.4085 ,  0.1425 , ...,  0.26035, 10.2    ,  3.     ],
       [ 0.66   ,  0.53   ,  0.1525 , ...,  0.32605, 10.6    ,  1.     ],
       ...,
       [ 0.4055 ,  0.3715 ,  0.112  , ...,  0.1598 ,  7.9    ,  2.     ],
       [ 0.5225 ,  0.4085 ,  0.1425 , ...,  0.26035, 10.2    ,  3.     ],
       [ 0.49   ,  0.39   ,  0.15   , ...,  0.17   , 21.     ,  3.     ]])

In [11]:
imputer.fit(X_train)
imputer.transform(X_test)

array([[ 0.4465 ,  0.195  ,  0.09   , ...,  0.0355 ,  9.     ,  2.     ],
       [ 0.5795 ,  0.4335 ,  0.153  , ...,  0.2421 , 10.8    ,  3.     ],
       [ 0.66   ,  0.53   ,  0.1575 , ...,  0.35295, 11.5    ,  1.     ],
       ...,
       [ 0.457  ,  0.3405 ,  0.11   , ...,  0.102  ,  7.9    ,  2.     ],
       [ 0.5795 ,  0.4335 ,  0.153  , ...,  0.2421 , 10.8    ,  3.     ],
       [ 0.49   ,  0.39   ,  0.15   , ...,  0.17   , 21.     ,  3.     ]])

In [12]:
imputer

KNNImputer(add_indicator=False, copy=True, metric='nan_euclidean',
           missing_values=nan, n_neighbors=10, weights='uniform')

In [45]:
KNNImputer()

KNNImputer(add_indicator=False, copy=True, metric='nan_euclidean',
           missing_values=nan, n_neighbors=5, weights='uniform')

In [14]:
imp = SimpleImputer(strategy = "mean")

In [47]:
SimpleImputer.__name__ +"_"+ imp.strategy

'SimpleImputer_mean'

In [48]:
type(imp.strategy)

str

In [49]:
imp_name = 

TypeError: join() takes exactly one argument (2 given)

In [50]:
flag = [1,1,1]
for i,_ in flag:
    print(i)

1
1
1


In [1]:
from sklearn.metrics import precision_recall_fscore_support
from sklearn.metrics import accuracy_score

In [2]:
test_md_y = [0, 1, 2, 2, 2]
predict_label = [0, 0, 2, 2, 1]

In [8]:
_, _, f1_macro, _ = precision_recall_fscore_support(test_md_y, predict_label, average='macro')
accuracy = accuracy_score(test_md_y, predict_label)


In [9]:
f1_macro

0.48888888888888893

In [10]:
accuracy

0.6

In [11]:
f1_micro

0.6

In [12]:
from sklearn.neighbors import KNeighborsClassifier

In [13]:
kneigh = KNeighborsClassifier(n_neighbors=10)

In [17]:
kneigh.__class__.__name__

'KNeighborsClassifier'

In [18]:
from sklearn import tree

In [19]:
clf = tree.DecisionTreeClassifier()

In [20]:
clf.__class__.__name__

'DecisionTreeClassifier'

In [24]:
import numpy as np

In [33]:
a = [1,2,3,4]

In [59]:
from numpy import savetxt
import csv 

In [60]:
std = np.std(a)

In [61]:
mean = np.mean(a)

In [72]:
a = [1,2,3,4,std,mean]

In [78]:
import csv

with open('newfilePath.csv', "w") as f:
    writer = csv.writer(f)
    for row in a:
        print(row)
        writer.writerow(str(row))

1
2
3
4
1.0481352526332528
2.269672331458316


In [69]:
savetxt('test.csv', a, delimiter=',')

In [1]:
import numpy as np

In [23]:
a = np.random.rand(10,4)
a

array([[0.71449961, 0.81447519, 0.4907141 , 0.67992064],
       [0.81390847, 0.7127158 , 0.43256118, 0.42323631],
       [0.35488431, 0.37801875, 0.56371913, 0.05130302],
       [0.7561533 , 0.71813108, 0.31901966, 0.6528093 ],
       [0.81438809, 0.71710077, 0.5404173 , 0.51221637],
       [0.24547296, 0.81299418, 0.22808699, 0.87745947],
       [0.6587409 , 0.82935171, 0.13483538, 0.11805721],
       [0.87016717, 0.12488407, 0.69198822, 0.76193006],
       [0.76682954, 0.06409884, 0.8306078 , 0.19675907],
       [0.55839986, 0.71917676, 0.12444165, 0.6897089 ]])

In [24]:
b = np.random.rand(6,4)
b

array([[0.14758937, 0.80613471, 0.04356243, 0.77873385],
       [0.80297753, 0.70425701, 0.82375147, 0.65660998],
       [0.65909254, 0.30470893, 0.51499962, 0.31389572],
       [0.42401596, 0.63437727, 0.31153405, 0.17580596],
       [0.27487432, 0.37354614, 0.6487247 , 0.15836202],
       [0.92498544, 0.46299832, 0.78782906, 0.43516988]])

In [20]:
b.reshape(10,1)

array([[0.21082405],
       [0.67578081],
       [0.72258117],
       [0.44091732],
       [0.93030267],
       [0.87066839],
       [0.93285181],
       [0.38898987],
       [0.09033245],
       [0.84830885]])

In [18]:
b

array([0.21082405, 0.67578081, 0.72258117, 0.44091732, 0.93030267,
       0.87066839, 0.93285181, 0.38898987, 0.09033245, 0.84830885])

In [25]:
np.concatenate((a,b), axis = 0)

array([[0.71449961, 0.81447519, 0.4907141 , 0.67992064],
       [0.81390847, 0.7127158 , 0.43256118, 0.42323631],
       [0.35488431, 0.37801875, 0.56371913, 0.05130302],
       [0.7561533 , 0.71813108, 0.31901966, 0.6528093 ],
       [0.81438809, 0.71710077, 0.5404173 , 0.51221637],
       [0.24547296, 0.81299418, 0.22808699, 0.87745947],
       [0.6587409 , 0.82935171, 0.13483538, 0.11805721],
       [0.87016717, 0.12488407, 0.69198822, 0.76193006],
       [0.76682954, 0.06409884, 0.8306078 , 0.19675907],
       [0.55839986, 0.71917676, 0.12444165, 0.6897089 ],
       [0.14758937, 0.80613471, 0.04356243, 0.77873385],
       [0.80297753, 0.70425701, 0.82375147, 0.65660998],
       [0.65909254, 0.30470893, 0.51499962, 0.31389572],
       [0.42401596, 0.63437727, 0.31153405, 0.17580596],
       [0.27487432, 0.37354614, 0.6487247 , 0.15836202],
       [0.92498544, 0.46299832, 0.78782906, 0.43516988]])

In [1]:
import pandas as pd

In [6]:
d = {'DTree': pd.Series([1,2,3,4], index=['KNN', 'MICE', 'Mean', 'Constant']),
    'KNN': pd.Series([5,8,3,4], index=['KNN', 'MICE', 'Mean', 'Constant'])}

In [7]:
df = pd.DataFrame(d)
df

DTree  KNN
KNN           1    5
MICE          2    8
Mean          3    3
Constant      4    4

In [12]:
a = [1,2,3]

In [17]:
b = pd.Series(a, index = ['1','2','3'])

In [19]:
b

1    1
2    2
3    3
dtype: int64

In [1]:
for i in range(3,5):
    print(i)

3
4


In [8]:
a = 5
for i in range(1, a):
    a -= 1 
    print(a)

4
3
2
1


In [ ]:
print()